### ISSUE TITLE
Fatal error: requestFeature() must be called before adding content

### ISSUE THREAD

**Issue by benadamstyles** [vkeepe/card.io#8]
Hey, this works great on iOS but getting the following on Android:

```
E/AndroidRuntime(14335): FATAL EXCEPTION: main
E/AndroidRuntime(14335): Process: com.swoonbox.dev.scanner, PID: 14335
E/AndroidRuntime(14335): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.swoonbox.dev.scanner/io.card.payment.DataEntryActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
E/AndroidRuntime(14335):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
E/AndroidRuntime(14335):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
E/AndroidRuntime(14335):    at android.app.ActivityThread.access$800(ActivityThread.java:155)
E/AndroidRuntime(14335):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
E/AndroidRuntime(14335):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(14335):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(14335):    at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime(14335):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14335):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(14335):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime(14335):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/AndroidRuntime(14335): Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
E/AndroidRuntime(14335):    at com.android.internal.policy.impl.PhoneWindow.requestFeature(PhoneWindow.java:302)
E/AndroidRuntime(14335):    at android.app.Activity.requestWindowFeature(Activity.java:3615)
E/AndroidRuntime(14335):    at io.card.payment.ui.ActivityHelper.addActionBarIfSupported(ActivityHelper.java:29)
E/AndroidRuntime(14335):    at io.card.payment.DataEntryActivity.onCreate(DataEntryActivity.java:395)
E/AndroidRuntime(14335):    at android.app.Activity.performCreate(Activity.java:6010)
E/AndroidRuntime(14335):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
E/AndroidRuntime(14335):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
E/AndroidRuntime(14335):    ... 10 more
W/ActivityManager(  832):   Force finishing activity 1 com.swoonbox.dev.scanner/io.card.payment.DataEntryActivity
W/ActivityManager(  832):   Force finishing activity 2 com.swoonbox.dev.scanner/io.card.payment.CardIOActivity
```

Also posting this on the Android SDK repo but if you have any ideas that would be a great help. Thank you.

**Comment by benadamstyles** [comment]
According to this: https://github.com/card-io/card.io-Android-SDK/issues/134 the version used in this plugin, `5.1.0`, might be the cause. Are you able to update it?

**Comment by lesterleong** [comment]
@Leeds-eBooks I've been getting this error while working in Appgyver Supersonic. Any ideas @vkeepe ?
